CREATE TABLE IF NOT EXISTS STORY (
    ID INT UNSIGNED AUTO_INCREMENT NOT NULL ,
    PARENT_ID INT UNSIGNED,
    TITLE_ID INT UNSIGNED,
    STORY_TEXT VARCHAR(100),
    INSERT_DATE DATETIME,
    UPDATE_DATE DATETIME,
    PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS TITLE (
    ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    TITLE_NAME VARCHAR(256),
    OVERVIEW VARCHAR(256),
    GENRE VARCHAR(256),
    INSERT_DATE DATETIME,
    UPDATE_DATE DATETIME,
    PRIMARY KEY (ID));
