CREATE TABLE IF NOT EXISTS TEST (
    ID INT UNSIGNED AUTO_INCREMENT NOT NULL ,
    NAME_TEST VARCHAR(64) NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    DEL_DATE DATETIME ,
    REG_USER VARCHAR(64) NOT NULL,
    UPD_USER VARCHAR(64),
    PRIMARY KEY (ID));

INSERT INTO TEST SELECT * FROM BAK_TEST;
DROP TABLE BAK_TEST;
