-- accountRole の CUD の機能を提供しない
CREATE TABLE IF NOT EXISTS account (
 accountNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
 mail VARCHAR (256) UNIQUE NOT NULL,
 hash VARCHAR (512),
 isOauthFlg TINYINT NOT NULL DEFAULT 0,
 accountRole TINYINT NOT NULL DEFAULT 0,
 passwordResetId VARCHAR (128),
 passwordResetLimit DATETIME,
 activate TINYINT NOT NULL DEFAULT 0,
 gmail VARCHAR (256) UNIQUE,
 regDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updDate DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(accountNo)
);

-- 認証拒否するトークンのハッシュ 登録されていれば認証を拒否する,expire で deleteする
-- 外部向けには CUD の機能を提供しない
CREATE TABLE IF NOT EXISTS ignoreToken (
  token VARCHAR(750) NOT NULL,
  expire DATETIME NOT NULL,
  PRIMARY KEY(token)
);

-- 再取得用長期トークンの格納、アカウントNOを持つ
CREATE TABLE IF NOT EXISTS longToken (
  token VARCHAR(750) NOT NULL,
  expire DATETIME NOT NULL,
  accountNo INT UNSIGNED NOT NULL,
  PRIMARY KEY(token)
);

-- サイト全体のリアルタイム変更可能な設定 CUD の機能を提供しない 1:true
-- CREATE TABLE IF NOT EXISTS siteSetting (
--   ignoreTokenDateTimeTo DATETIME, --この日時前のトークンはすべて拒否する
-- );

CREATE TABLE IF NOT EXISTS PREF (
 PREF_CD CHAR (2)  NOT NULL  ,
 PREF_NAME VARCHAR (8)  NOT NULL  ,
 PREF_NAME_KANA VARCHAR (24) NOT NULL,
 HIDE_FLG CHAR (1)  NOT NULL  ,
PRIMARY KEY(PREF_CD)
);

CREATE TABLE IF NOT EXISTS CITY (
 PREF_CD CHAR (2)  NOT NULL  ,
 CITY_CD CHAR (5)  NOT NULL  ,
 CITY_NAME VARCHAR (64)  NOT NULL  ,
 CITY_NAME_KANA VARCHAR (128) NOT NULL ,
 HIDE_FLG CHAR (1)  NOT NULL  ,
 DEL_DATE DATETIME
  DEFAULT NULL ,
PRIMARY KEY(PREF_CD,CITY_CD)
);

CREATE TABLE IF NOT EXISTS LINE (
 LINE_CD MEDIUMINT   NOT NULL  ,
 LINE_NAME VARCHAR (64)  NOT NULL  ,
 HIDE_FLG CHAR (1)  NOT NULL  ,
 DEL_DATE DATETIME
  DEFAULT NULL ,
PRIMARY KEY(LINE_CD)
);

CREATE TABLE IF NOT EXISTS STATION (
 STATION_CD INT  UNSIGNED  NOT NULL  ,
 STATION_G_CD INT  UNSIGNED NOT NULL  ,
 LINE_CD MEDIUMINT   NOT NULL  ,
 STATION_NAME VARCHAR (64)  NOT NULL  ,
 PREF_CD CHAR (2)  NOT NULL  ,
 CITY_CD CHAR (5)  NOT NULL  ,
 HIDE_FLG CHAR (1)  NOT NULL  ,
 DEL_DATE DATETIME
  DEFAULT NULL ,
PRIMARY KEY(STATION_CD, LINE_CD),
INDEX IDX_STATION_G_CD (STATION_G_CD),
INDEX IDX_STATION_PREF_CD (PREF_CD),
INDEX IDX_STATION_CITY_CD (CITY_CD)
);

CREATE TABLE IF NOT EXISTS DEFINITIONS (
  DEF_NO INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  CATEGORY VARCHAR (32) NOT NULL ,
  LABEL VARCHAR (64) NOT NULL ,
  INTEGRATE_NO INT ,
  REG_DATE DATETIME NOT NULL
    DEFAULT CURRENT_TIMESTAMP ,
  INTEGRATE_DATE DATETIME ,
  DEL_DATE DATETIME,
  UNIQUE (CATEGORY, LABEL),
  PRIMARY KEY(DEF_NO)
);

CREATE OR REPLACE VIEW V_DEFINITIONS AS
  SELECT * FROM DEFINITIONS WHERE INTEGRATE_NO IS NULL
  UNION ALL
  SELECT
    INTEGRATED_REC.DEF_NO as DEF_NO,
    INTEGRATED_REC.CATEGORY as CATEGORY,
    ACTIVE_REC.LABEL as LABEL,
    NULL as INTEGRATE_NO,
    INTEGRATED_REC.REG_DATE as REG_DATE,
    INTEGRATED_REC.INTEGRATE_DATE as INTEGRATE_DATE,
    NULL as DEL_DATE
  FROM
    (SELECT * FROM DEFINITIONS WHERE INTEGRATE_NO IS NOT NULL AND DEL_DATE IS NULL) INTEGRATED_REC
  INNER JOIN
    (SELECT * FROM DEFINITIONS WHERE INTEGRATE_NO IS NULL AND DEL_DATE IS NULL) ACTIVE_REC
  ON INTEGRATED_REC.INTEGRATE_NO = ACTIVE_REC.DEF_NO;

--S3 Presigned URL の有効期限を管理,同じリソースを複数回S3に発行依頼しないようにする
CREATE TABLE IF NOT EXISTS S3_URL_MANAGE (
  S3_KEY VARCHAR(64) NOT NULL ,
  URL VARCHAR(512)  NOT NULL  ,
  REG_DATE DATETIME NOT NULL
    DEFAULT CURRENT_TIMESTAMP ,
  EXPIRE_DATE DATETIME NOT NULL,
  DEL_DATE DATETIME,
  PRIMARY KEY(S3_KEY)
);

CREATE TABLE IF NOT EXISTS KV (
  K VARCHAR(64) NOT NULL,
  V TEXT,
  EXPIRE_DATE DATETIME NOT NULL,
  PRIMARY KEY(K)
);
